-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Pokemon CASCADE;
DROP TABLE IF EXISTS OmaPokemon CASCADE;
DROP TABLE IF EXISTS Kouluttaja CASCADE;
DROP TABLE IF EXISTS Liiga CASCADE;
DROP TABLE IF EXISTS Jasenyys CASCADE;